version: '3.4'

services:

    debts:
        build: debts/
        ports:
            - "2371:2371"
        depends_on:
            - debts-rabbit
            - psql-debts-debts
        networks:
            - smartdebt

    users:
        build: users/
        ports:
            - "1327:1327"
        depends_on:
            - psql-debts-users
        networks:
            - smartdebt


    front_server:
        build: front_server/
        ports:
            - "7111:7111"
        depends_on:
            - debts-rabbit
        networks:
            - smartdebt

    front_app:
        build: front/
        ports:
            - "2137:2137"
        networks:
            - smartdebt

    psql-debts-debts:
        image: postgres:latest
        ports:
            - "3721:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: debtsdb
        volumes:
            - db-data:/var/lib/postgresql/debtsdata
        networks:
            - smartdebt

    psql-debts-users:
        image: postgres:latest
        ports:
            - "3172:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        volumes:
            - db-data:/var/lib/postgresql/debtsdata
        networks:
            - smartdebt

    debts-rabbit:
        image: library/rabbitmq:latest
        ports:
            - "5672:5672"
        networks:
            - smartdebt

volumes:
    db-data:

networks:
    smartdebt:
        driver: bridge