create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
create table application_user (id  bigserial not null, password_hash varchar(255) not null, username varchar(255), primary key (id))
alter table application_user add constraint UK_6c0v0rco93sykgyetukfmkkod unique (username)
