create table user (id bigint generated by default as identity, password_hash varchar(255), username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table user (id bigint generated by default as identity, password_hash varchar(255), username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table user (id bigint generated by default as identity, password_hash varchar(255), username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table user (id bigint generated by default as identity, password_hash varchar(255), username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table user (id bigint generated by default as identity, password_hash varchar(255), username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table user (id bigint generated by default as identity, password_hash varchar(255) not null, username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table user (id bigint generated by default as identity, password_hash varchar(255) not null, username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table user (id bigint generated by default as identity, password_hash varchar(255) not null, username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table user (id bigint generated by default as identity, password_hash varchar(255) not null, username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table user (id bigint generated by default as identity, password_hash varchar(255) not null, username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table user (id bigint generated by default as identity, password_hash varchar(255) not null, username varchar(255), primary key (id))
create table user_debtors (user_entity_id bigint not null, debtors_id bigint not null)
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username)
alter table user_debtors add constraint UK_l1ts69k1fusrtvrvuub1fflnr unique (debtors_id)
alter table user_debtors add constraint FKex3u7qvg01qe99phfgial2ep8 foreign key (debtors_id) references user
alter table user_debtors add constraint FKhuie9cxni3bfjt6pv7vy4r1ea foreign key (user_entity_id) references user
create table USER (id bigint generated by default as identity, PASSWORD_HASH varchar(255) not null, USERNAME varchar(255), primary key (id))
create table USER_debtors (UserEntity_id bigint not null, debtors_id bigint not null)
alter table USER add constraint UK_lb5yrvw2c22im784wwrpwuq06 unique (USERNAME)
alter table USER_debtors add constraint UK_6ofj5ppq2i27wy22qu3g8woui unique (debtors_id)
alter table USER_debtors add constraint FK93sblnfy7wmw2os8q36b9bdwk foreign key (debtors_id) references USER
alter table USER_debtors add constraint FKrcqof300hd4vsdviorm9pgk44 foreign key (UserEntity_id) references USER
create table USER (id bigint generated by default as identity, PASSWORD_HASH varchar(255) not null, USERNAME varchar(255), primary key (id))
create table USER_debtors (UserEntity_id bigint not null, debtors_id bigint not null)
alter table USER add constraint UK_lb5yrvw2c22im784wwrpwuq06 unique (USERNAME)
alter table USER_debtors add constraint UK_6ofj5ppq2i27wy22qu3g8woui unique (debtors_id)
alter table USER_debtors add constraint FK93sblnfy7wmw2os8q36b9bdwk foreign key (debtors_id) references USER
alter table USER_debtors add constraint FKrcqof300hd4vsdviorm9pgk44 foreign key (UserEntity_id) references USER
create table USER (id bigint generated by default as identity, PASSWORD_HASH varchar(255) not null, USERNAME varchar(255), primary key (id))
create table USER_debtors (UserEntity_id bigint not null, debtors_id bigint not null)
alter table USER add constraint UK_lb5yrvw2c22im784wwrpwuq06 unique (USERNAME)
alter table USER_debtors add constraint UK_6ofj5ppq2i27wy22qu3g8woui unique (debtors_id)
alter table USER_debtors add constraint FK93sblnfy7wmw2os8q36b9bdwk foreign key (debtors_id) references USER
alter table USER_debtors add constraint FKrcqof300hd4vsdviorm9pgk44 foreign key (UserEntity_id) references USER
create table USER (id bigint generated by default as identity, PASSWORD_HASH varchar(255) not null, USERNAME varchar(255), primary key (id))
create table USER_debtors (UserEntity_id bigint not null, debtors_id bigint not null)
alter table USER add constraint UK_lb5yrvw2c22im784wwrpwuq06 unique (USERNAME)
alter table USER_debtors add constraint UK_6ofj5ppq2i27wy22qu3g8woui unique (debtors_id)
alter table USER_debtors add constraint FK93sblnfy7wmw2os8q36b9bdwk foreign key (debtors_id) references USER
alter table USER_debtors add constraint FKrcqof300hd4vsdviorm9pgk44 foreign key (UserEntity_id) references USER
