apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: debts
  name: debts
spec:
  ports:
    - protocol: TCP
      port: 2371
      targetPort: http
  selector:
    io.kompose.service: debts
    app: debts
    tier: backend