apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: users
  name: users
spec:
  ports:
  - name: "1327"
    port: 1327
    targetPort: 1327
  selector:
    io.kompose.service: users
  externalTrafficPolicy: Local